"""Data models for trading strategy framework."""

from dataclasses import dataclass, field
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Optional, Dict, Any, List
import uuid


class OrderSide(Enum):
    """Order side enumeration."""
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    """Order type enumeration."""
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class OrderStatus(Enum):
    """Order status enumeration."""
    PENDING = "PENDING"
    SUBMITTED = "SUBMITTED"
    PARTIAL = "PARTIAL"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class SignalStrength(Enum):
    """Signal strength levels."""
    WEAK = 0.3
    MEDIUM = 0.5
    STRONG = 0.8
    VERY_STRONG = 1.0


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Represents a potential trading opportunity with direction,
    strength, and risk parameters.
    """
    symbol: str
    direction: OrderSide
    strength: float  # 0.0 to 1.0
    timestamp: datetime
    strategy_name: str
    
    # Risk management
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    
    # Signal metadata
    signal_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    reason: str = ""
    confidence: float = 0.5
    
    # Technical indicator values at signal time
    indicators: Dict[str, float] = field(default_factory=dict)
    
    # Price levels
    entry_price: Optional[float] = None
    current_price: Optional[float] = None
    
    # Urgency and expiration
    urgency: str = "normal"  # "low", "normal", "high"
    expires_at: Optional[datetime] = None
    
    def __post_init__(self):
        """Validate signal data."""
        if not 0 <= self.strength <= 1:
            raise ValueError(f"Signal strength must be between 0 and 1, got {self.strength}")
        if not 0 <= self.confidence <= 1:
            raise ValueError(f"Confidence must be between 0 and 1, got {self.confidence}")
    
    def is_expired(self) -> bool:
        """Check if signal has expired."""
        if self.expires_at:
            return datetime.now() > self.expires_at
        return False
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'signal_id': self.signal_id,
            'symbol': self.symbol,
            'direction': self.direction.value,
            'strength': self.strength,
            'timestamp': self.timestamp.isoformat(),
            'strategy_name': self.strategy_name,
            'stop_loss': self.stop_loss,
            'take_profit': self.take_profit,
            'reason': self.reason,
            'confidence': self.confidence,
            'indicators': self.indicators,
            'entry_price': self.entry_price,
            'current_price': self.current_price,
            'urgency': self.urgency,
            'expires_at': self.expires_at.isoformat() if self.expires_at else None
        }


@dataclass
class Position:
    """
    Represents an open trading position.
    
    Tracks entry, current value, and P&L for an active position.
    """
    symbol: str
    side: OrderSide
    quantity: Decimal
    entry_price: Decimal
    entry_time: datetime
    
    # Current market data
    current_price: Decimal = Decimal('0')
    last_update: datetime = field(default_factory=datetime.now)
    
    # Risk management
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    
    # Position identification
    position_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    strategy_name: str = ""
    
    # Fees and costs
    entry_commission: Decimal = Decimal('0')
    
    def update_price(self, price: Decimal) -> None:
        """Update current price."""
        self.current_price = price
        self.last_update = datetime.now()
    
    @property
    def market_value(self) -> Decimal:
        """Calculate current market value."""
        return self.quantity * self.current_price
    
    @property
    def entry_value(self) -> Decimal:
        """Calculate entry value."""
        return self.quantity * self.entry_price
    
    @property
    def unrealized_pnl(self) -> Decimal:
        """Calculate unrealized P&L."""
        if self.side == OrderSide.BUY:
            return (self.current_price - self.entry_price) * self.quantity - self.entry_commission
        else:
            return (self.entry_price - self.current_price) * self.quantity - self.entry_commission
    
    @property
    def unrealized_pnl_pct(self) -> Decimal:
        """Calculate unrealized P&L percentage."""
        if self.entry_value == 0:
            return Decimal('0')
        return (self.unrealized_pnl / self.entry_value) * 100
    
    def is_profitable(self) -> bool:
        """Check if position is profitable."""
        return self.unrealized_pnl > 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'position_id': self.position_id,
            'symbol': self.symbol,
            'side': self.side.value,
            'quantity': str(self.quantity),
            'entry_price': str(self.entry_price),
            'entry_time': self.entry_time.isoformat(),
            'current_price': str(self.current_price),
            'last_update': self.last_update.isoformat(),
            'stop_loss': str(self.stop_loss) if self.stop_loss else None,
            'take_profit': str(self.take_profit) if self.take_profit else None,
            'strategy_name': self.strategy_name,
            'entry_commission': str(self.entry_commission),
            'market_value': str(self.market_value),
            'unrealized_pnl': str(self.unrealized_pnl),
            'unrealized_pnl_pct': str(self.unrealized_pnl_pct)
        }


@dataclass
class Trade:
    """
    Represents a completed trade (closed position).
    
    Contains full lifecycle data from entry to exit with P&L calculation.
    """
    symbol: str
    side: OrderSide
    quantity: Decimal
    
    # Entry details
    entry_price: Decimal
    entry_time: datetime
    
    # Exit details
    exit_price: Decimal
    exit_time: datetime
    
    # Optional fields with defaults
    entry_commission: Decimal = Decimal('0')
    exit_commission: Decimal = Decimal('0')
    
    # Trade identification
    trade_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    strategy_name: str = ""
    
    # Signal that triggered the trade
    signal_id: Optional[str] = None
    
    # Slippage tracking
    entry_slippage: Decimal = Decimal('0')
    exit_slippage: Decimal = Decimal('0')
    
    # Risk management execution
    stop_loss_hit: bool = False
    take_profit_hit: bool = False
    
    @property
    def gross_pnl(self) -> Decimal:
        """Calculate gross P&L before fees."""
        if self.side == OrderSide.BUY:
            return (self.exit_price - self.entry_price) * self.quantity
        else:
            return (self.entry_price - self.exit_price) * self.quantity
    
    @property
    def net_pnl(self) -> Decimal:
        """Calculate net P&L after fees."""
        return self.gross_pnl - self.entry_commission - self.exit_commission
    
    @property
    def net_pnl_pct(self) -> Decimal:
        """Calculate net P&L percentage."""
        entry_value = self.entry_price * self.quantity
        if entry_value == 0:
            return Decimal('0')
        return (self.net_pnl / entry_value) * 100
    
    @property
    def total_commission(self) -> Decimal:
        """Total commission paid."""
        return self.entry_commission + self.exit_commission
    
    @property
    def total_slippage(self) -> Decimal:
        """Total slippage cost."""
        return self.entry_slippage + self.exit_slippage
    
    @property
    def duration(self) -> float:
        """Trade duration in seconds."""
        return (self.exit_time - self.entry_time).total_seconds()
    
    def is_winner(self) -> bool:
        """Check if trade was profitable."""
        return self.net_pnl > 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'trade_id': self.trade_id,
            'symbol': self.symbol,
            'side': self.side.value,
            'quantity': str(self.quantity),
            'entry_price': str(self.entry_price),
            'entry_time': self.entry_time.isoformat(),
            'entry_commission': str(self.entry_commission),
            'exit_price': str(self.exit_price),
            'exit_time': self.exit_time.isoformat(),
            'exit_commission': str(self.exit_commission),
            'strategy_name': self.strategy_name,
            'signal_id': self.signal_id,
            'gross_pnl': str(self.gross_pnl),
            'net_pnl': str(self.net_pnl),
            'net_pnl_pct': str(self.net_pnl_pct),
            'total_commission': str(self.total_commission),
            'total_slippage': str(self.total_slippage),
            'duration': self.duration,
            'stop_loss_hit': self.stop_loss_hit,
            'take_profit_hit': self.take_profit_hit,
            'is_winner': self.is_winner()
        }


@dataclass
class Order:
    """
    Represents a trading order.
    
    Can be pending, submitted, filled, or cancelled.
    """
    symbol: str
    side: OrderSide
    quantity: Decimal
    order_type: OrderType
    
    # Order identification
    order_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    strategy_name: str = ""
    signal_id: Optional[str] = None
    
    # Price information
    price: Optional[Decimal] = None  # For limit orders
    stop_price: Optional[Decimal] = None  # For stop orders
    
    # Order state
    status: OrderStatus = OrderStatus.PENDING
    
    # Timestamps
    created_time: datetime = field(default_factory=datetime.now)
    submitted_time: Optional[datetime] = None
    filled_time: Optional[datetime] = None
    
    # Execution details
    filled_quantity: Decimal = Decimal('0')
    average_fill_price: Optional[Decimal] = None
    commission: Decimal = Decimal('0')
    
    # Risk management
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    
    # Time in force
    time_in_force: str = "DAY"  # "DAY", "GTC", "IOC", "FOK"
    
    def is_filled(self) -> bool:
        """Check if order is fully filled."""
        return self.status == OrderStatus.FILLED
    
    def is_active(self) -> bool:
        """Check if order is active."""
        return self.status in [OrderStatus.PENDING, OrderStatus.SUBMITTED, OrderStatus.PARTIAL]
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            'order_id': self.order_id,
            'symbol': self.symbol,
            'side': self.side.value,
            'quantity': str(self.quantity),
            'order_type': self.order_type.value,
            'strategy_name': self.strategy_name,
            'signal_id': self.signal_id,
            'price': str(self.price) if self.price else None,
            'stop_price': str(self.stop_price) if self.stop_price else None,
            'status': self.status.value,
            'created_time': self.created_time.isoformat(),
            'submitted_time': self.submitted_time.isoformat() if self.submitted_time else None,
            'filled_time': self.filled_time.isoformat() if self.filled_time else None,
            'filled_quantity': str(self.filled_quantity),
            'average_fill_price': str(self.average_fill_price) if self.average_fill_price else None,
            'commission': str(self.commission),
            'stop_loss': str(self.stop_loss) if self.stop_loss else None,
            'take_profit': str(self.take_profit) if self.take_profit else None,
            'time_in_force': self.time_in_force
        }