#!/usr/bin/env bash
set -euo pipefail

# Setup local dev environment for Autotrading
# Usage: ./setup_env.sh [--no-venv]

NO_VENV=false
for arg in "$@"; do
  case "$arg" in
    --no-venv) NO_VENV=true ;;
    -h|--help) echo "Usage: $0 [--no-venv]"; exit 0 ;;
    *) echo "Unknown option: $arg"; exit 1 ;;
  esac
done

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT_DIR"

# 1) Verify dependencies
need() { command -v "$1" >/dev/null 2>&1 || { echo "Missing dependency: $1"; exit 1; }; }
need bash
need npm
need brew

# Check for Python 3.11
if ! command -v python3.11 >/dev/null 2>&1; then
  echo "Python 3.11 not found. Installing via Homebrew..."
  brew install python@3.11
fi

# Check for PostgreSQL
if ! command -v pg_isready >/dev/null 2>&1; then
  echo "PostgreSQL not found. Installing via Homebrew..."
  brew install postgresql@16
fi

# Check for Redis
if ! command -v redis-cli >/dev/null 2>&1; then
  echo "Redis not found. Installing via Homebrew..."
  brew install redis
fi

# 2) Create .env if missing
if [[ ! -f .env ]]; then
  if [[ -f .env.template ]]; then
    echo "Creating .env from .env.template ..."
    cp .env.template .env
  else
    echo "Creating minimal .env ..."
    cat > .env << 'EOF'
# Autotrading .env generated by setup_env.sh
DB_USER=trading
DB_PASSWORD=trading123
DB_NAME=trading_db
# Optional: Provide Schwab App credentials (backend reads via environment)
# SCHWAB_API_KEY=
# SCHWAB_APP_KEY=
# SCHWAB_APP_SECRET=
# SCHWAB_CALLBACK_URL=http://127.0.0.1:8182/api/auth/callback
EOF
  fi
fi

# 3) Python virtualenv and backend deps (for local mode/testing)
if [[ "$NO_VENV" != "true" ]]; then
  VENV_PATH=".venv311"
  if [[ ! -d "$VENV_PATH" ]]; then
    echo "Creating Python 3.11 venv ($VENV_PATH) ..."
    python3.11 -m venv "$VENV_PATH"
  fi
  source "$VENV_PATH/bin/activate"
  echo "Using Python: $(which python) ($(python --version))"
  python -m pip install --upgrade pip setuptools wheel
  echo "Installing backend requirements ..."
  pip install -r requirements.txt
fi

# 4) Frontend deps (for local mode)
if [[ -d frontend ]]; then
  pushd frontend >/dev/null
  if [[ -f package-lock.json ]]; then
    npm ci
  else
    npm install
  fi
  popd >/dev/null
fi

# 5) Run database migrations (if alembic present)
if [[ -d src && -d alembic ]]; then
  if [[ -f alembic.ini ]]; then
    echo "Running migrations ..."
    # Ensure PostgreSQL is running
    if ! pg_isready -q 2>/dev/null; then
      echo "Starting PostgreSQL..."
      brew services start postgresql@16 2>/dev/null || brew services start postgresql 2>/dev/null
      sleep 3
    fi
    # Export database URL for alembic
    export DATABASE_URL=${DATABASE_URL:-"postgresql://houkjang@localhost/autotrading"}
    # Run migrations
    alembic upgrade head || echo "WARNING: migrations failed; ensure DB is available and config correct"
  fi
fi

echo "Environment setup complete."

