"""Add ticker candle and mining models

Revision ID: c91def111127
Revises: a3daa5437281
Create Date: 2025-08-25 00:54:39.074071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c91def111127'
down_revision = 'a3daa5437281'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('tier', sa.Enum('CORE', 'EXPANDED', 'DYNAMIC', name='tickertier'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_mined', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mining_status', sa.Enum('PENDING', 'MINING', 'COMPLETED', 'FAILED', name='miningstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('candles',
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('extended_hours', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('ticker_id', 'timestamp'),
    sa.UniqueConstraint('ticker_id', 'timestamp', name='_ticker_timestamp_uc')
    )
    op.create_index('idx_candles_ticker_timestamp', 'candles', ['ticker_id', 'timestamp'], unique=False)
    op.create_index('idx_candles_timestamp', 'candles', ['timestamp'], unique=False)
    op.create_table('mining_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('candles_expected', sa.Integer(), nullable=True),
    sa.Column('candles_received', sa.Integer(), nullable=True),
    sa.Column('gaps_detected', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'MINING', 'COMPLETED', 'FAILED', name='miningstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('api_calls', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', name='_ticker_date_uc')
    )
    op.create_index('idx_mining_history_date', 'mining_history', ['date'], unique=False)
    op.create_index('idx_mining_history_status', 'mining_history', ['status'], unique=False)
    # Drop tables in correct order to handle foreign key dependencies
    op.drop_index('ix_trades_status', table_name='trades')
    op.drop_index('ix_trades_strategy_id', table_name='trades')
    op.drop_index('ix_trades_symbol', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_positions_status', table_name='positions')
    op.drop_index('ix_positions_symbol', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_account_summary_date', table_name='account_summary')
    op.drop_table('account_summary')
    op.drop_index('idx_alerts_acknowledged', table_name='alerts')
    op.drop_index('idx_alerts_type_severity', table_name='alerts')
    op.drop_index('ix_alerts_alert_type', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('idx_price_data_symbol_timestamp', table_name='price_data')
    op.drop_index('ix_price_data_symbol', table_name='price_data')
    op.drop_table('price_data')
    # Drop backtests before strategies due to foreign key dependency
    op.drop_table('backtests')
    op.drop_table('strategies')
    op.drop_table('market_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('avg_volume_30d', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('volatility_30d', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('beta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sma_20', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('sma_50', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('sma_200', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('rsi_14', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='market_data_pkey'),
    sa.UniqueConstraint('symbol', name='market_data_symbol_key')
    )
    op.create_table('backtests',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('initial_capital', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('final_capital', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_return', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winning_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sharpe_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sortino_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_drawdown', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('var_95', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_win', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('avg_loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('profit_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('equity_curve', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trade_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name='backtests_strategy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='backtests_pkey')
    )
    op.create_table('strategies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('symbols', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winning_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pnl', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('sharpe_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_drawdown', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='strategies_pkey'),
    sa.UniqueConstraint('strategy_id', name='strategies_strategy_id_key')
    )
    op.create_table('price_data',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('open', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('high', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('low', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('close', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('vwap', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='price_data_pkey'),
    sa.UniqueConstraint('symbol', 'timestamp', name='price_data_symbol_timestamp_key')
    )
    op.create_index('ix_price_data_symbol', 'price_data', ['symbol'], unique=False)
    op.create_index('idx_price_data_symbol_timestamp', 'price_data', ['symbol', 'timestamp'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='alerts_pkey')
    )
    op.create_index('ix_alerts_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_index('idx_alerts_type_severity', 'alerts', ['alert_type', 'severity'], unique=False)
    op.create_index('idx_alerts_acknowledged', 'alerts', ['acknowledged'], unique=False)
    op.create_table('account_summary',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('starting_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('ending_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('cash_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('market_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('total_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('profitable_trades', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_volume', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('daily_pnl', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('daily_return', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cumulative_pnl', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('positions_held', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_position_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('margin_used', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='account_summary_pkey'),
    sa.UniqueConstraint('date', name='account_summary_date_key')
    )
    op.create_index('idx_account_summary_date', 'account_summary', ['date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BIGINT(), server_default=sa.text("nextval('positions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED', 'PARTIAL', name='positionstatus'), autoincrement=False, nullable=False),
    sa.Column('entry_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('entry_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('current_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('market_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('exit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('exit_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('realized_pnl', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('unrealized_pnl', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_pnl', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('stop_loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('take_profit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('max_loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='positions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_positions_symbol', 'positions', ['symbol'], unique=False)
    op.create_index('ix_positions_status', 'positions', ['status'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('BUY', 'SELL', 'BUY_TO_COVER', 'SELL_SHORT', name='orderaction'), autoincrement=False, nullable=False),
    sa.Column('order_type', postgresql.ENUM('MARKET', 'LIMIT', 'STOP', 'STOP_LIMIT', 'TRAILING_STOP', name='ordertype'), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('executed_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('executed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('commission', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('strategy_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('signal_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'FILLED', 'PARTIAL', 'CANCELLED', 'REJECTED', 'EXPIRED', name='orderstatus'), autoincrement=False, nullable=False),
    sa.Column('profit_loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('profit_loss_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('stop_loss', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('take_profit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('position_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name='trades_position_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='trades_pkey'),
    sa.UniqueConstraint('order_id', name='trades_order_id_key')
    )
    op.create_index('ix_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_strategy_id', 'trades', ['strategy_id'], unique=False)
    op.create_index('ix_trades_status', 'trades', ['status'], unique=False)
    op.drop_index('idx_mining_history_status', table_name='mining_history')
    op.drop_index('idx_mining_history_date', table_name='mining_history')
    op.drop_table('mining_history')
    op.drop_index('idx_candles_timestamp', table_name='candles')
    op.drop_index('idx_candles_ticker_timestamp', table_name='candles')
    op.drop_table('candles')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    # ### end Alembic commands ###